---
title: "abstract"
format: html
editor: visual
---

# Introduction

-   project motivation
-   data description
-   citation for data source
-   external research
-   how data were collected
-   variables of interest: percentage of pell students (control for tuiti), undergraduate students by family income
-   data cleaning process
-   any exploratory data analysis
-   research question
    -   What types of institutions best serve low-income students? Predicting

# Methodology

-   brief description of analysis process
-   reasoning for approach
-   model selection process
-   variable selection process
-   assessment of conditions and diagnositics
-   relevant considerations

# Results

-   key results from analysis
-   use model output to address research questions
-   use interpretations to support conclusions
-   focus on variables that help you answer the research question

# Discussion

-   summary of what was learned about reserach question
-   statistical arguments supporting conclusions
-   limitations of analysis
-   suggestions for im,porvement
-   issues with reliability and validity of data
-   ideas for future work

# Appendix
